name: UltimateAbilities
version: 1.0.0
author: Phoenix4041
website: https://github.com/Phoenix4041
main: Phoenix4041\UltimateAbilities\UltimateAbilities
api: 5.0.0
permissions:
  ultimateabilities.give:
    description: Permission to give ultimate abilities items
    default: op
  ultimateabilities.use:
    description: Permission to use ultimate abilities
    default: true
  ultimateabilities.reload:
    description: Permission to reload the plugin
    default: op    
