Aids:
  - "a"
  - "b"
  - "aids"
Alcohol:
  - "a"
  - "b"
  - "alcohol"
CheemsStick:
  - "a"
  - "b"
Cigar:
  - "a"
  - "b"
Coffe:
  - "a"
  - "b"
DisableEffects:
  - "a"
  - "b"
Drug:
  - "a"
  - "b"
Heart:
  - "a"
  - "b"
MegaInstinct:
  - "a"
  - "b"
Mota:
  - "a"
  - "b"
Phoenix:
  - "a"
  - "b"
Pots:
  - "a"
  - "b"
Redbull:
  - "a"
  - "b"
Resistance:
  - "a"
  - "b"
StormBreaker:
  - "a"
  - "b"
Strength:
  - "a"
  - "b"
TeleportAttack:
  - "a"
  - "b"
UltraInstinct:
  - "a"
  - "b"
Weakness:
  - "a"
  - "b"

